### ISSUE TITLE
Add possibility to deserialize to immutable object

### ISSUE THREAD

**Issue by jonaskello** [drails-dart/dson#2]
It would be nice if DSON supported immutable objects. I always make my data transfer objects immutable. This makes them safe to share in all code and also to cache. Here is an example:

``` dart
class FooDto {
  final Guid id;
  final String name;
  FooDto(this.id, this.name);
}
```

In order to deserialize the constructor must be called and the keys in the JSON matched to the names of the constructor params. I saw no examples of this (but have not tried so maybe it already works?).

**Comment by luisvt** [comment]
I'll try to implement that feature. However I would like to see a more explained sample why an inmutable object are safe to share in all code?

**Comment by jonaskello** [comment]
Immutable objects are nothing special, they are just read-only objects, and because they are read-only, nobody can ever change them and thus they can be shared by all code safely. One example why they are important: Consider the case where you have many developers working on a single project. If mutable objects are passed between different developers code, what can happen is the anti-pattern called "defensive copying". When one developer receives an object from code developed by another developer, he starts by copying it because he know the other developer's code still has a reference to it and may change properties on it without warning. Add more developers and a lot of the code base will do nothing more than doing copies...

Another example, consider making a query to the server and getting an object as response. Now we put this object in client-side cache so that next time the same query is issued, we need not access the server, we just return the object directly from the client-side cache. Consider some part of the code now gets this object from cache, and changes one of the properties. Since this is the same object as in cache, the cache also changes. So now the cache does not correspond to the query response anymore. This leads to very hard to find bugs. If the object were immutable, everyone can share the objects from the cache safely because no-one can change them.

Immutability has a lot more benefits than the above. Many of the new functional languages like ClojureScript have only immutable objects because of all the benefits it bring.

**Comment by luisvt** [comment]
1. Defensive Copying looks like a problem for multi-thread applications like java. If that the case, Dart is single-thread and many threats (functions, methods, classes) never would access the same object or property at the same time.
2. To me caching would also means that I want to write values to cache after send data to server or database. In other words, I would rewrite the values of cached objects after writing into the database. And also before write I would lock the object adding a new locked status. 

I still will implement the feature although I think is not needed.

**Comment by jonaskello** [comment]
Thanks for considering this feature!
1. Immutable objects are also useful for avoiding locks in multi-threading but as you say Dart is single threaded (but if I recall correctly they now have problems with mutable objects in sky applications). Defensive copying however is not related to this, it is more a matter of passing mutable objects between many layers of code developed by many different developers while having the guarantee that "your" copy of the object is not mutated by some other code. With immutable objects this is not necessary. So it is highly useful for single threaded apps. If you are interested, a team inside Google that use Dart have done this package to help with immutability, specifically stating the reason of avoiding defensive copying:
   https://pub.dartlang.org/packages/built_collection
   https://groups.google.com/a/dartlang.org/forum/#!searchin/misc/Introducing$20Built$20Collections/misc/2g2_yuaRgYU/3s41eigoY3AJ
   https://groups.google.com/a/dartlang.org/forum/#!topic/misc/k1px0Rt5HzA
2. With immutable objects, you just replace the whole object (or object graph) when you write to the cache.

**Comment by Pajn** [comment]
I would also love this feature.
Ran into this right now and I don't really know how to solve it in a good way. Having support in dson would be a nice way though.
