### ISSUE TITLE
Think about this: List of random typed objects

### ISSUE THREAD

**Issue by LexiBigCheese** [drails-dart/dson#21]
Think about a list of random typed objects.

how would you deal with them?

Maybe try storing their type name with them.

I did it, but i don't know how your code works so i can't put it in yours, but a push in the right direction might be

```dart
{
  'data': new SerializableBaconSomething(shouldDo:true,),
  'type': SerializableBaconSomething,
}
```

Also, look at my package: [server_client_comm](https://pub.dartlang.org/packages/server_client_comm)

**Comment by luisvt** [comment]
I'll take a look into it.

**Comment by LexiBigCheese** [comment]
i did it. myself. in my fork. i call it: Smart. it does it whenever it encounters a dynamic or an object. it stores the `runtimeType` in objects, but if in a map if you put a `runtimeType` key then it will become that type. it's cool though.

```dart
class A {
  Map x; //still will be a map, put types in there if you want
}

class B {
  dynamic x; //if was originally a map with a "runtimeType" key then it will be that type on deserialize
}
```
