### ISSUE TITLE
deserialize int to double if required

### ISSUE THREAD

**Issue by BorisNaguet** [drails-dart/dson#22]
Hello,

1st, thanks for this package that has been really helpful!

Now I have a little issue with JSON ints that I want to map to double (because I know this can be "1.5", but when it's "1.0" the server returns just "1").
It's rejected by:

```dart
else if (valueType == double) {
    if (value is double) {
      return value;
    } else {
      throw new IncorrectTypeTransform(value, 'double', key);
    }
  }
```

This could be:
```dart
else if (valueType == double) {
    if (value is double) {
      return value;
    } else if(value is int) {
     return value.toDouble();
  } else {
      throw new IncorrectTypeTransform(value, 'double', key);
    }
  }
```

The conversion is possible the other way (double => int) but it's much more dangerous. Here we just cast to a larger class.

**Comment by LexiBigCheese** [comment]
i shall add this to my fork.

**Comment by LexiBigCheese** [comment]
i have added this functionality.

**Comment by mitty1987** [comment]
This doesn't seem to work in the object:

**Comment by mitty1987** [comment]
This doesn't seem to work in the object...    "flutter: type 'int' is not a subtype of type 'double'"
override addAll method can help:
  @override
  addAll(Map map) {
    if (map != null)
      keys.forEach((key) {
        if (this[key] is double) {
          var value = map[key];
          if (value is int) {
            this[key] = value.toDouble();
          }
        }
      });
  }
but, I don't like this way....can you fix it? thank's.
