### ISSUE TITLE
How does the generic works?

### ISSUE THREAD

**Issue by yangxiaoweihn** [drails-dart/dson#31]
this library seems doesn't support generic.
```dart
library entity.ApiResponse;
import 'package:dson/dson.dart';

part 'ApiResponse.g.dart';
@serializable
class ApiResponse<T> extends _$ApiResponseSerializable{
    int code;
    String toast;
    String message;
    T data;
}
```
and i compile it ,it's wrong.
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following _CompileTimeError was thrown while handling a gesture:
'package:flutter_app/entity/ApiResponse.g.dart': error: line 70 pos 49: expression is not a valid
compile-time constant
    const DeclarationMirror(name: 'data', type: T);
                                                ^
When the exception was thrown, this was the stack:
#0      HttpInfoParseState.build.<anonymous closure> (package:flutter_app/http_parse.dart:40:25)
#1      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:323:14)
#2      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:375:30)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#4      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
#5      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
#6      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
#7      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
#8      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
#9      BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
#10     BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
#11     BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
#12     BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
#13     BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
#14     _invoke1 (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:127)
#15     _dispatchPointerDataPacket (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:85)
Handler: onTap
Recognizer:
  TapGestureRecognizer#bc3a2(debugOwner: GestureDetector, state: possible, won arena, finalPosition:
  Offset(47.7, 103.3), sent tap down)

**Comment by LexiBigCheese** [comment]
that would take lots (and i mean lots!) of work. unless...

we generate a classMirror constructor for each class!

woah! then my code could be cut down! hehehe! i'm gonna implement that! hehehe! hohoho! hahaha!

actually... maybe later.

but that's how i'd go about doing it!

**Comment by LexiBigCheese** [comment]
but in the meantime, get rid of the generic and store it's type as a string, to get the type all you need to do is `classMirrors.keys.where((x) => x.toString() == PUTTYPESTRINGHERE)` or if you use my fork, just store the variable and when you need to ask for it's runtimeType. as my fork has what i call 'smartness'.

literally. with `fromMap(toMap(x))` `x` keeps it's type.

**Comment by LexiBigCheese** [comment]
thinking about it... the analyzer wouldn't give two sh*ts about it's type if extracted from json or a map, only if you state it...

so all i need to do is add type arguments to the `fromX` functions? and make the generator not care about these generics?

wow.

**Comment by LexiBigCheese** [comment]
Ok, so it was really nothing to do with dson, just the built_mirrors and serializable libraries. i added stuff to all 3 libraries though, so i could have the fix + actually have the fix be useful. will commit and push soon.

**Comment by LexiBigCheese** [comment]
try using the 

`git: https://github.com/dwaindibbly/dson.git`
`git: https://github.com/dwaindibbly/built_mirrors.git`
`git: https://github.com/dwaindibbly/serializable.git`

and 

```yaml
dependency_overrides:
  built_mirrors:
    git: https://github.com/dwaindibbly/built_mirrors.git
```

versions. then build. then try doing the things with them. and when using the `fromX` functions, add the type to make the analyzer check values and stuff!. (so it looks like `fromX<A<B>>(var)`)

**Comment by LexiBigCheese** [comment]
ok, so my version will work... but add `<T>` to `_$ApiResponseSerializable` to get this:

```dart
library entity.ApiResponse;
import 'package:dson/dson.dart';

part 'ApiResponse.g.dart';
@serializable
class ApiResponse<T> extends _$ApiResponseSerializable<T>{
    int code;
    String toast;
    String message;
    T data;
}
```

**Comment by luisvt** [comment]
Serialization of generics objects is now supported, However deserialization still not fully supported. For example you can do next:

```dart
library example.generics;

import 'dart:convert';

import 'package:dson/dson.dart';

part 'serialize_generic.g.dart';

@serializable
class Page<T> extends _$PageSerializable<T> {
  int size;

  int total;

  int number;

  List<T> items;
}

@serializable
class Person extends _$PersonSerializable {
  int id;

  String name;
}

main() {
  _initMirrors();

  var p = new Person()
    ..id = 1
    ..name = 'person 1';

  var page = new Page()
    ..size = 1
    ..number = 1
    ..total = 100
    ..items = [p];

  var jsonStr = toJson(page);
  print('jsonStr: $jsonStr');

  // Deserialization still is not supported completly. Next code is a workaround of how to do it:
  var page2Map = jsonDecode(jsonStr);
  page2Map['items'] = fromMap(page2Map['items'], [() => List<Person>(), Person]);
  var page2 = Page<Person>()..fromMap(page2Map);

  print('page2.size: ${page2.size}');
  print('page2.number: ${page2.number}');
  print('page2.total: ${page2.total}');
  print('page2.items[0].id: ${page2.items[0].id}');
  print('page2.items[0].name: ${page2.items[0].name}');
}
```

**Comment by luisvt** [comment]
I just released a new version containing a better handling of this:

https://github.com/dart-league/dson#serializedeserialize-generic-objects

```dart
library example.generics;

import 'package:dson/dson.dart';

part 'generics.g.dart';

@serializable
class Page<T> extends _$PageSerializable<T> {
  int size;

  int total;

  int number;

  List<T> items;
}

@serializable
class Person extends _$PersonSerializable {
  int id;

  String name;
}

main() {
  _initMirrors();

  var p = new Person()
    ..id = 1
    ..name = 'person 1';

  var page = new Page<Person>()
    ..size = 1
    ..number = 1
    ..total = 100
    ..items = [p];

  var jsonStr = toJson(page);
  print('jsonStr: $jsonStr');

  Page<Person> page2 = fromJson(jsonStr, [() => Page<Person>(), {'items': [() => List<Person>(), Person]}]);

  print('page2.size: ${page2.size}');
  print('page2.number: ${page2.number}');
  print('page2.total: ${page2.total}');
  print('page2.items[0].id: ${page2.items[0].id}');
  print('page2.items[0].name: ${page2.items[0].name}');
```
