### ISSUE TITLE
Update `serializable_core` dependency version in pubspec

### ISSUE THREAD

**Issue by jagged3dge** [drails-dart/dson#32]
I tried this package just today and ran into the 'Missing concrete implementations of Map methods' error. 

I noticed it stemmed from the `serializable_core` package, and you've since pushed a new release for it. 
I suggest you please update the `dson`'s pubspec as well, so us users can pull the new version :+1: 

Thanks for your efforts!

**Comment by luisvt** [comment]
yes, I'm still working on this. Sorry for the inconveniences.
