### ISSUE TITLE
recommend updates to readme/install

### ISSUE THREAD

**Issue by diablodale** [drails-dart/dson#35]
Given a standard flutter install, and a new user, I recommend some updated to the `README.md` for setup/install and initial usage.

1. The user needs to add `build_runner` as a dev_dependency within their `pubspec.yaml`. For example
    ```yaml
    dev_dependencies:
      build_runner:
    ```
2. The pre-build command is slightly different with the flutter toolset. The following is used instead: `flutter packages pub run build_runner build`
3. The relationship of the `library` naming, the `part` naming, and the current requirement to have them all in a single file with the `main()` function can be difficult to learn at the beginning. I recommend a review of these topics along with their limitations due to https://github.com/drails-dart/dson/issues/30. Afterwards, to clarify the README.

**Comment by troyzhao** [comment]
build_runner: ^xxxx  is missing again in the README.md

**Comment by luisvt** [comment]
Sorry, I will add it again
