### ISSUE TITLE
Convert Lists<ModelClass> to ModelClass objects is incorrect

### ISSUE THREAD

**Issue by troyzhao** [drails-dart/dson#40]
I notice that use 'fromMap' to convert json who contain list Model to dart List Model is not work.

It works OK, after i modify some code. 

1. the following illustrate is Inappropriately

   
<img width="789" alt="image" src="https://user-images.githubusercontent.com/3151615/45485969-132fbc00-b78c-11e8-9136-6579f2ca5ab9.png">

    it should be: 
     List<Person> persons = fromMap([{"id": 1, "name": "John Doe"}], [List<Person>(), Person]);

2. modify the '_convertValue' function code in deserializer.dart of dson_core
    
<img width="398" alt="image" src="https://user-images.githubusercontent.com/3151615/45485844-9ac8fb00-b78b-11e8-9874-bce91bf1726a.png">
  append ' = valueType[0]; ' after 'var receiver'

Then it works well.

BTW: i think the Map conversion has same issue.

**Comment by luisvt** [comment]
sorry, it is a legacy documentation problem, the correct way of converting should be:

```dart
List<Person> persons = fromMap([{"id": 1, "name": "John Doe"}], [() => List<Person>(), Person]);
```
