### ISSUE TITLE
NoSuchMethodError The method 'forEach' was called on null

### ISSUE THREAD

**Issue by mitty1987** [drails-dart/dson#45]
I has a json `{"code":"90009","msg":"test","resultData":null}`, the `resultData` is an object,
and the type is
```dart
$mkType = [
      () => CommonBean<LoginToken>(),
      {
        $keyCommonBean1: [() => LoginToken(), LoginToken]
      }
    ];
```
If `resultData` is not null, there has no error

**Comment by luisvt** [comment]
Please upgrade to the latest version
