### ISSUE TITLE
Unable to generate _initMirrors()

### ISSUE THREAD

**Issue by Presheda** [drails-dart/dson#49]
serialization fails as _initMirrors() could not be generated

**Comment by luisvt** [comment]
Can you show an example?

**Comment by Presheda** [comment]
I'm doing this 

`import 'package:dson/dson.dart';

part 'delivery_location.g.dart';

@serializable
class Location extends _$LocationSerializable{
   String locationName;
   double locationPrice;
   String documentId;

   Location({this.locationName, this.locationPrice, this.documentId});
}`


but i'm unable to get **_initMirrors()** to be generated

**Comment by luisvt** [comment]
`_initMirror` can only be generated if there is a `main` function present
