### ISSUE TITLE
Property annotation conflicts with Polymer 1.0 Property annotation

### ISSUE THREAD

**Issue by mlesin** [drails-dart/dson#7]
I know it's easy to workaround importing dson library with 'as' keyword, just thinking maybe it would be better to avoid this at all by renaming it to something else, like DsonProperty, for example.
But think twice about that because it would be a breaking change. May be it would be enough to put a note about that in the docs.

**Comment by luisvt** [comment]
Yep, I will do that

**Comment by luisvt** [comment]
I think calling **DsonProperty** will be too tied to the framework, what do you think if we called **SerializableProperty**?

**Comment by luisvt** [comment]
Or maybe better **SerializedName**, since at the end that annotation is to rewrite the name of the property after serialization.

**Comment by mlesin** [comment]
I like **SerializedName** more too :)
